cc_library(
    name = "01.12.2023",
    hdrs = ["Matrix.h"],
    srcs = ["Matrix.cpp"],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "test_app_for_01.12.2023",
    srcs = ["FileName.cpp"],
    deps = ["01.12.2023"],
)
